version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: astrolabe
      POSTGRES_PASSWORD: hi123
      POSTGRES_DB: astrolabe
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
